const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=require('node:path').resolve(__dirname,'..');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(base+'/agenda/regras-agenda.js','utf8'),c);
const units=[{id:'limoeiro',city:'Limoeiro',active:true,frequency:14,base:'2026-05-11',weekday:1,periods:['manha','tarde']},{id:'carpina',city:'Carpina',active:true,frequency:14,base:'2026-05-11',weekday:1,periods:['tarde']}];
function schedule(exceptions,explicit=[]){return c.AgendaRegional.resolve({today:'2026-10-03',units,exceptions,explicit},30);}
const extra={unitId:'limoeiro',date:'2026-10-08',period:'dia_todo',type:'extra'};
assert.equal(schedule([extra]).filter(s=>s.date==='2026-10-08').length,2);
assert.equal(schedule([extra,{...extra,type:'suspend',period:'manha'}]).filter(s=>s.date==='2026-10-08').length,1);
assert.equal(schedule([extra,{...extra,type:'suspend'}]).filter(s=>s.date==='2026-10-08').length,0);
assert.equal(schedule([{...extra,type:'suspend'},extra]).filter(s=>s.date==='2026-10-08').length,2);
assert.equal(schedule([extra,extra]).filter(s=>s.date==='2026-10-08').length,2);
const timed={...extra,period:'horario',time:'14:30'};
assert.equal(schedule([timed,{...timed,type:'suspend',time:'14:00'}]).filter(s=>s.date==='2026-10-08').length,1);
assert.equal(schedule([timed,{...timed,type:'suspend'}]).filter(s=>s.date==='2026-10-08').length,0);
assert.equal(schedule([timed,{...extra,type:'suspend',period:'tarde'}]).filter(s=>s.date==='2026-10-08').length,0);
assert.equal(schedule([], [{unitId:'limoeiro',date:'2026-10-12',status:'fechada',period:'Dia todo'}]).filter(s=>s.date==='2026-10-12'&&s.unitId==='limoeiro').length,0);
const inactive=JSON.parse(JSON.stringify(units));inactive[0].active=false;
assert.equal(schedule([],[{unitId:'limoeiro',date:'2099-02-10',period:'Manhã',status:'aberta'}]).filter(s=>s.date.startsWith('2099')).length,0);
assert.equal(c.AgendaRegional.resolve({today:'2026-10-03',units:inactive,exceptions:[extra]}).filter(s=>s.unitId==='limoeiro').length,0);
assert.ok(c.AgendaRegional.preview({action:'swap',source:{unitId:'limoeiro',date:'2026-10-08',period:'manha'},target:{unitId:'carpina',date:'2026-10-09',period:'tarde'}},units).includes('09/10/2026'));

let stored='',writes=0,lockAvailable=true,uuid=0;
const sheet={getLastRow:()=>stored?2:1,getRange:(a,...args)=>({getValue:()=>stored,setValue:(value)=>{if(a==='A2'){stored=value;writes++;}},getValues:()=>[['Limoeiro','Limoeiro','SIM'],['Carpina','Carpina','SIM']]})};
const ss={getSheetByName:()=>sheet,insertSheet:()=>sheet};
const server={PropertiesService:{getScriptProperties:()=>({getProperty:()=>null})},SpreadsheetApp:{openById:()=>ss,flush:()=>{}},LockService:{getScriptLock:()=>({tryLock:()=>lockAvailable,releaseLock:()=>{}})},Utilities:{getUuid:()=>String(++uuid)},CFG_AGENDA:{SHEET_ID:'test',ABA_CLINICAS:'clinicas'},CAB_AGENDA:Array(9),agendaSheet_:()=>({getLastRow:()=>1}),normalizar:s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),salaHoje_:()=> '2026-10-03',salaDataStr_:s=>s};
vm.createContext(server);vm.runInContext(fs.readFileSync(base+'/backend/AjustesAgenda.js','utf8'),server);
const admin={usuario:'lucas',perfil:'amplo'},other={usuario:'intruso',perfil:'amplo'};
const payload={action:'swap',revision:0,requestId:'operation-test-0001',internalNote:'INTERNA_SECRETA',source:{unitId:'limoeiro',date:'2026-10-08',period:'manha'},target:{unitId:'carpina',date:'2026-10-09',period:'tarde'},createdBy:'intruso'};
assert.equal(server.ajusteSalvar_(payload,null).ok,false);
assert.equal(server.ajusteSalvar_(payload,other).ok,false);
assert.equal(server.ajusteSalvar_(payload,{usuario:'lucas',perfil:'restrito'}).ok,false);
assert.equal(writes,0);
lockAvailable=false;assert.equal(server.ajusteSalvar_(payload,admin).ok,false);assert.equal(writes,0);lockAvailable=true;
assert.equal(server.ajusteSalvar_({...payload,target:{...payload.target,date:'2026-02-31'}},admin).ok,false);assert.equal(writes,0);
assert.equal(server.ajusteSalvar_(payload,admin).ok,true);assert.equal(writes,1);
const doc=JSON.parse(stored);assert.equal(doc.exceptions.length,2);assert.equal(doc.exceptions[1].date,'2026-10-09');assert.equal(doc.exceptions[0].createdBy,'lucas');
assert.equal(server.ajusteSalvar_(payload,admin).repeated,true);assert.equal(writes,1);
assert.equal(server.ajusteSalvar_({...payload,requestId:'operation-test-0002'},admin).conflict,true);assert.equal(writes,1);
const publicData=server.ajustePublico_();assert.equal(publicData.exceptions.length,2);assert.ok(!JSON.stringify(publicData).includes('INTERNA_SECRETA'));assert.ok(!JSON.stringify(publicData).includes('createdBy'));
assert.equal(server.ajusteAdmin_(other).ok,false);
assert.equal(server.ajustePodeEditar_({usuario:'andrea',perfil:'amplo'}),true);
for(const file of ['agenda-publica.js','ajuste-rapido.js','regras-agenda.js','AjustesAgenda.js'])new vm.Script(fs.readFileSync(base+(file==='AjustesAgenda.js'?'/backend/':'/agenda/')+file,'utf8'));
console.log('OK: turnos, dia todo, horários, unidades inativas, reabertura, atomicidade, autorização, datas inválidas, lock, idempotência, conflitos e privacidade.');
